name: "Kubeflow - Echo Pipeline"
description: "Test to illustrate making components correctly."
inputs:
  - {name: Echo, type: String, default: 'Echo pipeline is functional'}
outputs:
  - {name: Output, type: String }
implementation:
  container:
    image: k8scc01covidacr.azurecr.io/echo
    command: [
      /echo.sh, {inputValue: Echo},
    ]
    fileOutputs:
      Output: /tmp